# Schema for the configuration files of the Give module.

give.settings:
  type: config_object
  label: 'Give Settings'
  mapping:
    default_form:
      type: string
      label: 'Default Form'
    stripe_secret_key:
      type: string
      label: 'Stripe secret API key'
    stripe_publishable_key:
      type: string
      label: 'Stripe publishable API key'
    flood:
      type: mapping
      label: 'flood control'
      mapping:
        limit:
          type: integer
          label: 'Limit'
        interval:
          type: integer
          label: 'Interval'
    api_key_dwolla:
          type: string
          label: 'Dwolla API key'
    send_receipt:
      type: boolean
      label: 'Send a receipt if e-mail address provided'


give.form.*:
  type: config_entity
  label: 'Give form'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    recipients:
      type: sequence
      label: 'Recipients'
      sequence:
        type: email
        label: 'Email address'
    subject:
      type: string
      label: 'Subject'
    reply:
      type: text
      label: 'Auto-reply'
    check_or_other_text:
      type: string
      label: 'Check or other text'
    credit_card_extra_text:
      type: string
      label: 'Credit card extra text'
    collect_address:
      type: boolean
      label: 'Collect address with credit card, check, or other'
    weight:
      type: integer
      label: 'Weight'
    redirect_uri:
      type: string
      label: 'Redirect page'
    submit_text:
      type: string
      label: 'Submit button text'
    payment_submit_text:
      type: string
      label: 'Submit payment button text'
    donate_encouragement_text:
      type: string
      label: 'Donate encouragement text'
    frequencies:
      type: sequence
      label: 'Frequencies'
      sequence:
        type: mapping
        label: 'Frequency'
        mapping:
          interval:
            type: string
            label: 'Interval'
          interval_count:
            type: integer
            label: 'Interval Count'
          description:
            type: 'string'
            label: 'Description'
