# Schema for the configuration files of the Give module.

give.settings:
  type: config_object
  label: 'Give Settings'
  mapping:
    default_form:
      type: string
      label: 'Default Form'
    stripe_secret_key:
      type: string
      label: 'Stripe secret API key'
    stripe_publishable_key:
      type: string
      label: 'Stripe publishable API key'
    flood:
      type: mapping
      label: 'flood control'
      mapping:
        limit:
          type: integer
          label: 'Limit'
        interval:
          type: integer
          label: 'Interval'
    api_key_dwolla:
          type: string
          label: 'Dwolla API key'
    send_receipt:
      type: boolean
      label: 'Send a receipt if e-mail address provided'


give.form.*:
  type: config_entity
  label: 'Give form'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    recipients:
      type: sequence
      label: 'Recipients'
      sequence:
        type: email
        label: 'Email address'
    reply:
      type: text
      label: 'Auto-reply'
    weight:
      type: integer
      label: 'Weight'
    check_or_other_text:
      type: string
      label: 'Check or other test'
    subject:
      type: string
      label: 'Subject'
